### ISSUE TITLE
Avoid using trigger_error for deprecations

### ISSUE THREAD

**Issue by nickdnk** [lcobucci/jwt#565] opened 2020-11-26 22:14 UTC
Hello

I upgraded from 3.3 to 3.4, which broke my app (in testing of course, but still).

I'd suggest you do not suddenly introduce calling `trigger_error` in a minor version, as it will break some systems set up to strictly handle notices or warnings as errors - such as ours.

Deprecations are obviously fine, but please only do it with phpdocs and/or documentation.

https://github.com/lcobucci/jwt/blob/320b9f05741b24acbbaf1106ed267ff3817fd74d/src/Token.php#L289-L302

I will be making the migration to 4.x now anyway, but please avoid this in the future.

**Comment by Ocramius** [comment] 2020-11-26 22:19
Duplicate of https://github.com/lcobucci/jwt/issues/550#issuecomment-733557709

**Closed by Ocramius** 2020-11-26 22:19 UTC
