### ISSUE TITLE
How to use json privatekey

### ISSUE THREAD

**Issue by lovearthhome** [lcobucci/jwt#235] opened 2018-05-12 09:23 UTC
my private key is in such a format, which cannot tobe read by keychain->getPriateKey(*)

how to deal with this private key

`{"kty":"RSA","kid":"88483727556929xxxxxxxx9904351185815489","alg":"ES256","n":"ie0IKvKLd7Y3izHcZemdDsVVXg5QtWtGF7XEkILnn66R2\_3a30DikqV409OVL7Hv0ElACgCaBLEgZeGHTcdLE1xxDTna8MMBnBNuMVghvFERCKh8uzpxlQsfcnFd5IFdJWj1x5Tscetrow6lA3h5zYx0rF5TkZzC4DclxgDmITRam0dsHBxr3uk9m9YYBz2mX0ehjY0xxxxlaA4P9OFAO4au9-zcVQop9vLirxdwDedk2p-F9GP6UiQC9V2LTWqkVw\_oPBf9Rlh8Qdi19jA8SeCfzAxJZYlbOTK8dYAFAVEFsvXCFvdaxQefwWFw","e":"AQAB"}`

**Comment by lovearthhome** [comment] 2018-05-12 09:43
is there any way to put the privatekey json as php constant?


![_20180512174442](https://user-images.githubusercontent.com/16535358/39956064-f8bc6120-560b-11e8-87d6-991cb67e8abc.png)

**Comment by lcobucci** [comment] 2018-05-13 23:51
@lovearthhome you're trying to use a JWK, which currently not supported #32. So for now, if you want to use this lib, you'd need to convert the JWK into private/public keys. There're other libraries that support it.

**Comment by lovearthhome** [comment] 2018-05-15 08:58
@Ocramius 
use `composer require mdanter/ecc` and then move the files to where?

**Comment by Ocramius** [comment] 2018-05-15 08:59
@lovearthhome no need to move anything

**Comment by lovearthhome** [comment] 2018-05-15 09:02
is this right?
`
[u1@EevX vendor]$ ls
autoload.php  composer  fgrosse  lcobucci  mdanter
`

**Comment by Ocramius** [comment] 2018-05-15 09:02
Yeap, that should be it :+1:

**Comment by lovearthhome** [comment] 2018-05-15 09:03
Error happens on:

`
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Lcobucci\JWT\Signer\Ecdsa\KeyParser::__construct() must be an instance of Mdanter\Ecc\Math\MathAdapterInterface, instance of Mdanter\Ecc\Math\GmpMath given, called in /jwt_lcobucci/jwt/vendor/lcobucci/jwt/src/Signer/Ecdsa.php on line 50 and defined in /var/www/html/agi.xdua.com/jwt_lcobucci/jwt/vendor/lcobucci/jwt/src/Signer/Ecdsa/KeyParser.php:43
Stack trace:
#0 /jwt_lcobucci/jwt/vendor/lcobucci/jwt/src/Signer/Ecdsa.php(50): Lcobucci\JWT\Signer\Ecdsa\KeyParser->__construct(Object(Mdanter\Ecc\Math\GmpMath))
#1 /jwt_lcobucci/test_jwt2.php(9): Lcobucci\JWT\Signer\Ecdsa->__construct()
#2 {main}
  thrown in /jwt_lcobucci/jwt/vendor/lcobucci/jwt/src/Signer/Ecdsa/KeyParser.php on line 43

`

**Comment by Ocramius** [comment] 2018-05-15 09:04
Hmm... @lcobucci do yo remember which version of `mdanter/ecc` was needed?

Btw, we should probably get rid of the optional dependency, even if it removes `Ecdsa` support.

**Comment by Spomky** [comment] 2018-05-15 11:37
Hi @lovearthhome,

As explained in the issue to opened (see https://github.com/web-token/jwt-framework/issues/122), the problem is that you are using an RSA key with an EC algorithm

**`"kty":"RSA"`*** with **`"alg":"ES256"`** are incompatible.

If you want to use your RSA key, then you have to use a RSA based algorithm.
If you absolutely need to use the ES256 algorithm, then you have to generate a new key on the P-256 curve.

**Comment by lcobucci** [comment] 2018-06-24 22:45
@Ocramius once you review #247 I can port it back to v3.3.x and then we'll get rid of it.

**Comment by Ocramius** [comment] 2018-06-24 23:02
Reviewed

**Comment by lcobucci** [comment] 2019-10-12 04:15
Stable `v3.3.x` has already been released and we can safely close this.

**Closed by lcobucci** 2019-10-12 04:15 UTC

**Comment by superbikebig** [comment] 2025-03-24 06:55
> is there any way to put the privatekey json as php constant?
> 
> ![_20180512174442](https://user-images.githubusercontent.com/16535358/39956064-f8bc6120-560b-11e8-87d6-991cb67e8abc.png)
