### ISSUE TITLE
Error when adding secret

### ISSUE THREAD

**Issue by RenatoPta** [lcobucci/jwt#148] opened 2016-12-08 20:20 UTC
Using the code from example:

```php
use Lcobucci\JWT\Configuration;

$config = new Configuration();
$signer = $config->getSigner(); // Default signer is HMAC SHA256

$token = $config->createBuilder()
                ->issuedBy('http://example.com') // Configures the issuer (iss claim)
                ->canOnlyBeUsedBy('http://example.org') // Configures the audience (aud claim)
                ->identifiedBy('4f1g23a12aa', true) // Configures the id (jti claim), replicating as a header item
                ->issuedAt(time()) // Configures the time that the token was issue (iat claim)
                ->canOnlyBeUsedAfter(time() + 60) // Configures the time that the token can be used (nbf claim)
                ->expiresAt(time() + 3600) // Configures the expiration time of the token (exp claim)
                ->with('uid', 1) // Configures a new claim, called "uid"
                ->sign($signer, 'testing') // creates a signature using "testing" as key
                ->getToken(); // Retrieves the generated token


var_dump($token->verify($signer, 'testing 1')); // false, because the key is different
var_dump($token->verify($signer, 'testing')); // true, because the key is the same
```

I get the following error:

```
Fatal error: Uncaught TypeError: Argument 2 passed to Lcobucci\JWT\Builder::sign() must be an instance of Lcobucci\JWT\Signer\Key, string given, called in D:\Projetos\JWT-PHP\teste.php on line 18 and defined in D:\Projetos\JWT-PHP\Lcobucci\JWT\Builder.php:245 
Stack trace: 
#0 D:\Projetos\JWT-PHP\teste.php(18): Lcobucci\JWT\Builder->sign(Object(Lcobucci\JWT\Signer\Hmac\Sha256), 'testing') 
#1 {main} thrown in D:\Projetos\JWT-PHP\Lcobucci\JWT\Builder.php on line 245
```

Is there anything I'm doing wrong?

**Comment by RenatoPta** [comment] 2016-12-09 01:24
I changed the type Key to String in second paramter "$key" in file Lcobucci\JWT\Builder.php:245 and it worked

**Comment by lcobucci** [comment] 2016-12-09 07:25
@RenatoPta the problem is that the documentation is outdated and you're using an unstable version. 
A lot of things will change (as you can see on #129), including the documentation. 

If you are fine with that and don't mind changing your code until v4 is released you should not change the library's code and just pass an instance of `Key` instead of a `string`.

Although I appreciate people trying things out on the development version I'd recommend you to use v3. 2.

**Comment by lcobucci** [comment] 2016-12-09 07:28
Closing as `won't fix` since the documentation is going to be up on the validation refactoring PR

**Closed by lcobucci** 2016-12-09 07:28 UTC
Labels: documentation, wontfix
