### ISSUE TITLE
error Undefined method 'claims'.

### ISSUE THREAD

**Issue by linxue** [lcobucci/jwt#1008] opened 2023-04-19 03:41 UTC
error: 
Undefined method 'claims'.

php code : 
$jwtData['created'] = $jwtParseRes->claims()->get('created');

suggest:
in file lcobucci/jwt/src/Token.php , add these code: 

    /**
     * return claims DataSet
     */
    public function claims(): DataSet;

**Comment by lcobucci** [comment] 2023-04-19 05:03
Duplicate of https://github.com/lcobucci/jwt/issues/611?

**Closed as not planned** 2023-04-19 17:36 UTC
Labels: Duplicate
