### ISSUE TITLE
No change to composer.json, but a composer update result in "Key provided is shorter than 256 bits, only 240 bits provided" error

### ISSUE THREAD

**Issue by dev-mansonthomas** [lcobucci/jwt#987] opened 2022-12-26 00:38 UTC
Hi,

I've updated my project using "composer update -a -o" without updating anything in my composer.json

"lcobucci/jwt": "^4.1.5", (actual is 4.2.1)

and after deploying my project I get the following error at login : 

"Key provided is shorter than 256 bits, only 240 bits provided" 

I'm not sure it's legit that the code breaks after such update, but anyhow, what is the fix to this issue ? 

Thanks,
Thomas

```
   "exception": {
            "message": "Key provided is shorter than 256 bits, only 240 bits provided",
            "stackTrace": "
#0 /workspace/vendor/lcobucci/jwt/src/Signer/Hmac.php(19): LcobucciJWTSignerInvalidKeyProvided::tooShort(256, 240)
#1 /workspace/vendor/lcobucci/jwt/src/Token/Builder.php(119): LcobucciJWTSignerHmac->sign('eyJ0eXAiOiJKV1Q...', Object(LcobucciJWTSignerKeyInMemory))
#2 /workspace/src/routes/routesActions/authentication/AuthenticateAbstractAction.php(75): LcobucciJWTTokenBuilder->getToken(Object(LcobucciJWTSignerHmacSha256), Object(LcobucciJWTSignerKeyInMemory))
#3 /workspace/src/routes/routesActions/authentication/AuthenticateAction.php(118): RedCrossQuestroutesroutesActionsauthenticationAuthenticateAbstractAction->getToken(Object(RedCrossQuestEntityQueteurEntity), Object(RedCrossQuestEntityUniteLocaleEntity), Object(RedCrossQuestEntityUserEntity))
```

The related code : 

```
    Configuration::class => function (ContainerInterface $c):Configuration
    {
      $jwtSecret     = $c->get(SecretManagerService::class)->getSecret(SecretManagerService::$JWT_SECRET);
      $signer        = new Sha256();
      $key           = InMemory::plainText($jwtSecret);
      $configuration = Configuration::forSymmetricSigner($signer, $key);

      $configuration->setValidationConstraints(
          new Lcobucci\JWT\Validation\Constraint\IssuedBy    ($c->get('settings')['jwt']['issuer'  ]),
          new Lcobucci\JWT\Validation\Constraint\PermittedFor($c->get('settings')['jwt']['audience']),
          new Lcobucci\JWT\Validation\Constraint\SignedWith  ($signer, $key)
      );

      return $configuration;
    },
```

```
protected function getToken(QueteurEntity $queteur, UniteLocaleEntity $ul, UserEntity $user) : Token
  {

    $issuer         = $this->settings['jwt'        ]['issuer'        ];
    $audience       = $this->settings['jwt'        ]['audience'      ];
    $deploymentType = $this->settings['appSettings']['deploymentType'];
    $sessionLength  = $this->settings['appSettings']['sessionLength' ];

    $now    = new DateTimeImmutable();

    return $this->JWTConfiguration->builder()
      ->issuedBy          ($issuer  ) // Configures the issuer (iss claim)
      ->permittedFor      ($audience)
      ->issuedAt          ($now)
      ->canOnlyBeUsedAfter($now->modify('+1 minute'))
      ->expiresAt         ($now->modify("+$sessionLength hour"))
      ->withClaim         ('username' , $queteur->nivol)
      ->withClaim         ('id'       , $user->id      )
      ->withClaim         ('ulId'     , $queteur->ul_id)
      ->withClaim         ('ulName'   , $ul->name      )
      ->withClaim         ('ulMode'   , $ul->mode      )
      ->withClaim         ('queteurId', $queteur->id   )
      ->withClaim         ('roleId'   , $user->role    )
      ->withClaim         ('d'        , $deploymentType)
      ->getToken          ($this->JWTConfiguration->signer() , $this->JWTConfiguration->signingKey());
  }
```

**Comment by Ocramius** [comment] 2022-12-26 08:59
Duplicate of #890

**Closed as completed by Ocramius** 2022-12-26 08:59 UTC
Labels: Duplicate

**Comment by dev-mansonthomas** [comment] 2022-12-31 15:20
A few of remarks : 
* Changelog states a minor breaking change, but there's no indication is given on how to change the code so that it's working again with best solution. Can you add a link to a page that indicates how to change the project so that it works safely ?
* It also states "for people who don't follow RFC"... I'm pretty sure I've used sample code from the this project's documentation... 
* The documentation do not mention what to do either. It just list algorithm and unsafe/deprecated algorithm.  My code is **not** using the unsafe algorithm and still it breaks after upgrade. I obviously don't want to switch to an unsafe implementation, so how do I get the code working from here ? 

Google the error message just did bring up some Chinese website with no solution, it would be nice to mention the error "Key provided is shorter than 256 bits, only 240 bits provided" and the correction that should be done in both changelog & documentation, so that the solution is easy to find in google.

Also, I'm no security expert, I thank you for all the work you put into this project, and that's why I use it, so I don't have to be a security expert. But really here, I've no clue of what to do. It's a project I'm developing since 2016, and this project is one of many pieces of it. 

Can you help on how to change my code so that it's safe & running ?

**Comment by Ocramius** [comment] 2022-12-31 15:24
You really just need a longer/stronger signing key, that's all :)

**Comment by dev-mansonthomas** [comment] 2022-12-31 16:00
Ohhh :) too simple is too complicated some time 😂
Thanks

**Comment by dev-mansonthomas** [comment] 2022-12-31 16:30
It's working again :) Thank a lot !
