### ISSUE TITLE
Question / Builder `getToken`

### ISSUE THREAD

**Issue by donatj** [lcobucci/jwt#223] opened 2018-03-01 19:56 UTC
I am curious, is the stable 3.x release still open to changes?

A problem we're having is that we need to know if the builder has a claim set or not. 

We are using the stable branch. The builder itself has no 'hasClaim' method.

```php
$tmpToken = $builder->getToken();
if( $tmpToken->hasClaim('blah') ) {
    // …
}
```

The problem with this is `$builder->getToken();` eagerly builds the payload. This is a waste of CPU.

I have three proposals, but my prefered one may be API breaking:

1. Add a `hasClaim` method to the `Builder` - easy but maybe overkill?
2. Add `getEncoder`/`setEncoder` to the `Builder` - then I could simply create a `NullEncoder` that avoids the work.
3. Make the token payload building no longer eager - and instead build on `__toString` - this is my prefered solution but is probably API breaking.

**Comment by lcobucci** [comment] 2018-03-01 21:38
> I am curious, is the stable 3.x release still open to changes?

@donatj it's kind of open 😄 I'm currently the only person maintaining the lib and my main focus is to finish and release `v4.0`. My main concern is that everything that we potentially add to `v3.3.0` we will have to port to `v4.0`, so I'm trying to do things in the other way around (add to `v4.0` and potentially port to `v3.3.0`).

> The problem with this is `$builder->getToken();` eagerly builds the payload. This is a waste of CPU.

The design of the `Builder` component is to follow the design pattern "builder", so the `Builder#getToken()` was intended to only be called once you have everything set in the builder.

> 1. Add a hasClaim method to the Builder - easy but maybe overkill?
> 2. Add getEncoder/setEncoder to the Builder - then I could simply create a NullEncoder that avoids the work.
> 3. Make the token payload building no longer eager - and instead build on `__toString` - this is my prefered solution but is probably API breaking.

Your ideas definitely work, however they create some accidental complexity or design issues that I'd love to not have to deal with (specially changing the immutability factor of the token)... 

But before of jumping into conclusions or possible solutions I would like to hear a bit more about the problem itself, I mean, why exactly do you have the need to know in a later stage which claims have been previously set by you?

**Comment by lcobucci** [comment] 2018-06-24 22:48
@donatj closing due to lack of interaction, please reopen if you'd like to discuss it a bit more.

**Closed by lcobucci** 2018-06-24 22:48 UTC
Labels: Question
