### ISSUE TITLE
JWT version 4.0.0: How to validate if token is expired

### ISSUE THREAD

**Issue by meSmashsta** [lcobucci/jwt#627] opened 2021-01-10 19:05 UTC
I am using version 4.0.0

```
config = Configuration::forSymmetricSigner(
    new Sha256(),
    InMemory::plainText('key')
);

$now = new DateTimeImmutable();
$tokenStr = $config->builder()
                 ->issuedBy('issuer')
                 ->permittedFor('subject')
                 ->issuedAt($now)
                 ->canOnlyBeUsedAfter($now)
                 ->expiresAt($now) // it expires now but below it passes the validAt constraint
                 ->withClaim('uid', $uid)
                 ->getToken($this->config->signer(), $this->config->signingKey())
                 ->toString();

// verifying part...

$tokenArr = explode('.', $tokenStr)
$token = $config->parser()->parse(
    "{$tokenArr[0]}.{$tokenArr[1]}.{$tokenArr[2]}"
);
$constraints = [
    new ValidAt(SystemClock::fromUTC())
];
$is_valid = $config->validator()->validate($token, ...$constraints);
assert($is_valid) // it always says it's valid instead of not valid...
```
Even if I create an expired token by setting the expires at as today 

I also noticed in the docu that there are two constraint classes that checks the  iat, nbf, and exp:

```
Lcobucci\JWT\Validation\Constraint\StrictValidAt

Lcobucci\JWT\Validation\Constraint\LooseValidAt
```

But only ValidAt.php is the only available class that deals with iat, nbf, and exp in the package directory:
![image](https://user-images.githubusercontent.com/12151336/104132673-d571eb00-53b9-11eb-89d1-a40f022dc02b.png)

**Comment by DuckHunter213** [comment] 2021-01-10 23:09
```
expiresAt($time + 3600) // Configures the expiration time of the token (exp claim)
$token->getClaim('exp')
```
maybe you can use the claim for validate the token, i think when you uses valid, is if the token general is valid 

this is my solution to get the expiration of the token
```
the $token->getClaim('exp') returns you a time() 🤔
print_r(date('m/d/Y H:i:s', $token->getClaim('exp')));
```

I hope to help you ;3

**Comment by meSmashsta** [comment] 2021-01-11 03:11
> ```
> expiresAt($time + 3600) // Configures the expiration time of the token (exp claim)
> $token->getClaim('exp')
> ```
> 
> maybe you can use the claim for validate the token, i think when you uses valid, is if the token general is valid
> 
> this is my solution to get the expiration of the token
> 
> ```
> the $token->getClaim('exp') returns you a time() 🤔
> print_r(date('m/d/Y H:i:s', $token->getClaim('exp')));
> ```
> 
> I hope to help you ;3

Thank you for the reply, I'll try this. So at the moment there are no constraint that does this for us? :o Is it possible I make one and make a PR for this? :o

**Comment by meSmashsta** [comment] 2021-01-11 05:06
The `getClaim/1` method wasn't found, we probably have different versions. Anyway this is how I did it:

```
    function isValid(Plain $token) {
        $constraints = $this->validationConstraints();
        return ! $this->config->validator()->validate($token, ...$constraints) &&
                ! $token->isExpired(new DateTimeImmutable());
    }
```

```
    private function validationConstraints() {
        return [
            new IdentifiedBy(SimpleJWT::ISS),
            new PermittedFor(SimpleJWT::AUD)
        ];
    }
```

**Comment by lcobucci** [comment] 2021-01-11 10:37
@meSmashsta your initial code is correct but if you're issuing and verifying in one go (like in your script), ~there a chance that `$now` and the time yielded by the clock will point to the same second, which will consider the token as valid.~ after looking it again, it seems you're having issues due to using different timezones.

Try this:

```php
$config = Configuration::forSymmetricSigner(
    new Sha256(),
    InMemory::plainText('key')
);

$clock = SystemClock::fromUTC(); // use the clock for issuing and validation
$now = $clock->now();
$tokenStr = $config->builder()
                 ->issuedBy('issuer')
                 ->permittedFor('subject')
                 ->issuedAt($now)
                 ->canOnlyBeUsedAfter($now)
                 ->expiresAt($now) // it expires now but below it passes the validAt constraint
                 ->withClaim('uid', 'some id')
                 ->getToken($config->signer(), $config->signingKey())
                 ->toString();

// verifying part...

// $tokenArr = explode('.', $tokenStr) // There's no need to explode the token, that is part of the parsing process.
$token = $config->parser()->parse($tokenStr);

/*$constraints = [
    new ValidAt(SystemClock::fromUTC())
];*/ // if you have only on constraint, than this bit is unnecessary.

var_dump($config->validator()->validate($token, new ValidAt($clock)) === false);
```

> I also noticed in the docu that there are two constraint classes that checks the iat, nbf, and exp:
> 
> ```
> Lcobucci\JWT\Validation\Constraint\StrictValidAt
> Lcobucci\JWT\Validation\Constraint\LooseValidAt
> ```
> 
> But only ValidAt.php is the only available class that deals with iat, nbf, and exp in the package directory:

You may have read the docs for the next release (4.1.x-dev). On the stable things are correct: https://lcobucci-jwt.readthedocs.io/en/stable/validating-tokens/#available-constraints

**Comment by lcobucci** [comment] 2021-01-11 10:46
>    function isValid(Plain $token) {
>         $constraints = $this->validationConstraints();
>         return ! $this->config->validator()->validate($token, ...$constraints) &&
>                 ! $token->isExpired(new DateTimeImmutable());
>     }

That confirms my theory of different timezones, here you're using your default timezone (which is probably not set to `UTC`).

If you DO want to rely on your default timezone to handle your tokens, create the clock instance using `SystemClock::fromSystemTimezone()` instead of `SystemClock::fromUTC()`

**Comment by lcobucci** [comment] 2021-01-11 10:56
I'm intrigued, though. AFAIK PHP handled different timezone comparison transparently for users...

**Comment by lcobucci** [comment] 2021-01-11 11:13
Okay, it's indeed handled transparently. Your code behaves properly on my development environment (exception is thrown on the assertion), with some minor syntax fixes.

I just cannot reproduce what you're reporting here and would really recommend you not to have the `isValid()` method/function.

**Comment by meSmashsta** [comment] 2021-01-12 12:21
For brevity I put the generating of access token and its validation in one place but in reality they are both in separate functions.

The `$now` datetime is used only for generating the access token for the user.

On the part that I verify if the token's ISS and AUD is valid and that the EXP that the token is not expired.

Thanks for pointing out the parsing part, I explode it because I saw in the documentation that they concatenated the token string before passing it to the parse function.

Thank you for clearing things up! Can't wait to refactor my code! Hope it works for me 😊

**Comment by lcobucci** [comment] 2021-01-27 23:45
@meSmashsta I'll close this one. Please let us know if you've found any issue here.

**Closed as completed by lcobucci** 2021-01-27 23:45 UTC
Labels: Bug, Missing tests

**Comment by meSmashsta** [comment] 2021-02-03 04:30
Hi just to give some updates, I upgraded to the latest version which is 4.1 and used `LooseValidAt` for the expiration validation. I also continued using `SystemClock::fromUTC()` since I wanted it to be time zone less if that makes sense. Code looks something like this:

```
$config->validator()->validate($token, ...validationConstraints());
```

```
function validationConstraints() {
    return [
        new IssuedBy($this->iss),
        new PermittedFor($this->aud),
        new LooseValidAt(SystemClock::fromUTC())
    ];
}
```
