### ISSUE TITLE
Add claims() function to token interface

### ISSUE THREAD

**Issue by christopherboisvert** [lcobucci/jwt#1044] opened 2024-01-27 01:13 UTC
Hi ! Whenever I open my code where I get the claims out of the token. PHP can't find the claims function in the interface and mark it as not existing. I suggest adding it in Token.php interface so the error won't be shown.

Example of modified Token.php : 
```php
declare(strict_types=1);

namespace Lcobucci\JWT;

use DateTimeInterface;
use Lcobucci\JWT\Token\DataSet;

interface Token
{
    /**
     * Returns the token headers
     */
    public function headers(): DataSet;

    /**
     * Returns the token claims
     */
    public function claims(): DataSet;

    /**
     * Returns if the token is allowed to be used by the audience
     *
     * @param non-empty-string $audience
     */
    public function isPermittedFor(string $audience): bool;

    /**
     * Returns if the token has the given id
     *
     * @param non-empty-string $id
     */
    public function isIdentifiedBy(string $id): bool;

    /**
     * Returns if the token has the given subject
     *
     * @param non-empty-string $subject
     */
    public function isRelatedTo(string $subject): bool;

    /**
     * Returns if the token was issued by any of given issuers
     *
     * @param non-empty-string ...$issuers
     */
    public function hasBeenIssuedBy(string ...$issuers): bool;

    /**
     * Returns if the token was issued before of given time
     */
    public function hasBeenIssuedBefore(DateTimeInterface $now): bool;

    /**
     * Returns if the token minimum time is before than given time
     */
    public function isMinimumTimeBefore(DateTimeInterface $now): bool;

    /**
     * Returns if the token is expired
     */
    public function isExpired(DateTimeInterface $now): bool;

    /**
     * Returns an encoded representation of the token
     *
     * @return non-empty-string
     */
    public function toString(): string;
}
```

**Comment by Ocramius** [comment] 2024-01-27 03:01
Note: adding methods to an interface is a major BC break, so we'd need a new interface for that

**Comment by Slamdunk** [comment] 2024-01-27 11:20
Duplicate of https://github.com/lcobucci/jwt/issues/611 and https://github.com/lcobucci/jwt/pull/186

**Closed as not planned by Slamdunk** 2024-01-27 11:20 UTC
Labels: Duplicate

**Comment by Slamdunk** [comment] 2024-01-27 11:40
I suggest you to use the `JwtFacade` (https://lcobucci-jwt.readthedocs.io/en/stable/quick-start/) that already return an `UnencryptedToken` with the `claims()` method declared.

**Comment by christopherboisvert** [comment] 2024-01-28 18:00
Hi ! Thanks for all the reference issues guys. I will look at the JwtFacade, I did not know this existed. I will implement that in all my projects hehe 👍
