### ISSUE TITLE
nbf and other claims using MicrosecondBasedDateConversion results in string in JWT token

### ISSUE THREAD

**Issue by sakarikl** [lcobucci/jwt#628] opened 2021-01-11 11:34 UTC
If MicrosecondBasedDateConversion convertDate gets input parameter with microseconds returned result is string in format "123456789.12345"

RFC in this case is quite hard to read as it seems that you can read in way that only numbers are allowed or practically any format, depending how you interpret the wording.

Many (most) js jwt handling libraries reject this as it is not numeric type in js but a string

This issue for us came from league/oauth2-server, but the underlying issue seems to be in here.

**Comment by sakarikl** [comment] 2021-01-11 11:43
`NumericDate`

`      A JSON numeric value representing the number of seconds from
      1970-01-01T00:00:00Z UTC until the specified UTC date/time,
      ignoring leap seconds.  This is equivalent to the IEEE Std 1003.1,
      2013 Edition [POSIX.1] definition "Seconds Since the Epoch", in
      which each day is accounted for by exactly 86400 seconds, other
      than that non-integer values can be represented.  See RFC 3339
      [RFC3339] for details regarding date/times in general and UTC in
      particular.`
      
All those date fields are supposed to be in this NumericDate format, which seems to be unixtime and not microtimes added to it. Unless this part allows practically every format imaginable: `other than that non-integer values can be represented` 

From: https://tools.ietf.org/html/rfc7519#section-4.1.5

**Comment by Ocramius** [comment] 2021-01-11 13:32
Dupe of https://github.com/lcobucci/jwt/issues/604#issuecomment-741915901 ?

**Comment by lcobucci** [comment] 2021-01-11 14:13
And https://github.com/lcobucci/jwt/discussions/623

**Closed as completed by lcobucci** 2021-01-11 14:13 UTC
Labels: Duplicate
