### ISSUE TITLE
Allow an array for audience

### ISSUE THREAD

**Issue by waltertamboer** [lcobucci/jwt#560] opened 2020-11-26 08:46 UTC
Hi,

I appreciate your work a lot! Thank you!

I ran into an issue where it's not allowed to set an array as audience. I believe this is not in line with the specs:

> In the general case, the "aud" value is an array of case-sensitive strings, each containing a StringOrURI value.  In the special case when the JWT has one audience, the "aud" value MAY be a single case-sensitive string containing a StringOrURI value.

https://tools.ietf.org/html/draft-ietf-oauth-json-web-token-32#section-4.1.3

https://github.com/lcobucci/jwt/blob/3.4/src/Builder.php#L111
https://github.com/lcobucci/jwt/blob/master/src/Validation/Constraint/PermittedFor.php#L14

Thanks again for your hard work.

**Comment by b-water** [comment] 2020-11-26 08:49
Hey, i got the same Issue. Audience in JWT is an Array with Element 0, but the lib tries to compare it to a string.

**Comment by lcobucci** [comment] 2020-11-26 09:07
@waltertamboer v3.x is supposed to only support a single entry in the `aud`, in v4.x you may set multiple entries by calling `Builder#permittedFor()` [multiple times or with multiple elements](https://github.com/lcobucci/jwt/blob/6d8665ccd924dc076a9b65d1ea8abe21d68f6958/src/Token/Builder.php#L35-L41#L20).

If you do need multiple entries on `aud` you should upgrade to v4.0.

> Hey, i got the same Issue. Audience in JWT is an Array with Element 0, but the lib tries to compare it to a string.

@b-water that looks like a bug during the backport 🤦 would be able to send a PR with a test reproducing the issue?

**Comment by waltertamboer** [comment] 2020-11-26 09:13
Thanks! Will upgrade and try it out.

**Comment by b-water** [comment] 2020-11-26 11:07
@lcobucci hope this helps!

**Comment by lcobucci** [comment] 2020-11-26 11:16
@b-water it does, thanks ❤️

**Comment by lcobucci** [comment] 2020-11-27 01:02
Handled by d446df1fa1b61e8d35a901779988f2574b23c150 (v4.0 only).

Closing here, folks.

**Closed by lcobucci** 2020-11-27 01:02 UTC
