### ISSUE TITLE
validation of token

### ISSUE THREAD

**Issue by purohitvijay** [lcobucci/jwt#190] opened 2017-08-05 13:48 UTC
validationData class always return true value. what is reason behind this. please give me solution as soon as possible

**Comment by lcobucci** [comment] 2017-08-06 08:38
@purohitvijay I'm sorry but it's impossible to give any solution without knowing exactly what you're doing. Can you provide more information?

**Comment by purohitvijay** [comment] 2017-08-08 05:13
@lcobucci  Hi i wiil send my code please check that.

$token = (new Lcobucci\JWT\Builder())->setIssuer('http://example.com') // Configures the issuer (iss claim)
                                ->setAudience('http://example.com') // Configures the audience (aud claim)
                                ->setId('4f1g23a12aa', true) // Configures the id (jti claim), replicating as a header item
                                ->setIssuedAt(time()) // Configures the time that the token was issue (iat claim)
                                ->setExpiration(time() + 3600) //Configures the expiration time of the token (nbf claim)
                                ->set('uid', 11) // Configures a new claim, called "uid"
                                ->getToken(); // Retrieves the generated token


                        $token->getHeaders(); // Retrieves the token headers
                        $token->getClaims(); // Retrieves the token claims
                        $oauthToken = $token;
                        $oauthTokenNew = ((string) $oauthToken);


if (!empty($oauthTokenNew))
                            {
                                $token = (new Lcobucci\JWT\Parser())->parse((string) $oauthTokenNew); // Parses from a string
                                $token->getHeaders(); // Retrieves the token header
                                $token->getClaims(); // Retrieves the token claims
                                $data = new Lcobucci\JWT\ValidationData(); // It will use the current time to validate (iat, nbf and exp)
                                $data->setIssuer('http://example.com');
                                $data->setAudience('http://example.com');
                                $data->setId('4f1g23a12aa');
                                $validate = $token->validate($data);
                                if ($validate == 1)
{
echo 'validate';
}
else
{
echo 'error';
}

In this the value of $validate is always 1.

**Comment by Ocramius** [comment] 2017-08-08 08:34
Cleaned up the code a bit:

```php
$oauthToken = (new Lcobucci\JWT\Builder())
    ->setIssuer('http://example.com')
    ->setAudience('http://example.com')
    ->setId('4f1g23a12aa', true)
    ->setIssuedAt(time())
    ->setExpiration(time() + 3600)
    ->set('uid', 11)
    ->getToken();

$token = (new Lcobucci\JWT\Parser())
    ->parse((string) $oauthToken);

$data = new Lcobucci\JWT\ValidationData();
$data->setIssuer('http://example.com');
$data->setAudience('http://example.com');
$data->setId('4f1g23a12aa');

var_dump($token->validate($data));
```

This seems correct, and this code should always dump `true`.

**Comment by Ocramius** [comment] 2017-08-08 08:35
Here's the same code, but this version should dump `false`:

```php
$oauthToken = (new Lcobucci\JWT\Builder())
    ->setIssuer('http://example.com')
    ->setAudience('http://example.com')
    ->setId('4f1g23a12aa', true)
    ->setIssuedAt(time())
    ->setExpiration(time() + 5)
    ->set('uid', 11)
    ->getToken();

sleep(10);

$token = (new Lcobucci\JWT\Parser())
    ->parse((string) $oauthToken);

$data = new Lcobucci\JWT\ValidationData();
$data->setIssuer('http://example.com');
$data->setAudience('http://example.com');
$data->setId('4f1g23a12aa');

var_dump($token->validate($data));
```

**Comment by purohitvijay** [comment] 2017-08-08 09:07
@Ocramius , Thanx for your replay but why this code always dump true, when we give the expiration time.

**Comment by Ocramius** [comment] 2017-08-08 12:44
Tge second example shouldn't

**Comment by purohitvijay** [comment] 2017-08-10 07:27
@lcobucci please replay as soon as possible because I need to implement this code on my project. Other wise suggest me another way to implement this functionality.

**Comment by Ocramius** [comment] 2017-08-10 07:42
@purohitvijay you just got a reply on this: the code example in https://github.com/lcobucci/jwt/issues/190#issuecomment-320889845

This is how you reproduce it:

```sh
git clone git@github.com:lcobucci/jwt.git
cd jwt
git checkout 3.2.1
curl -sS https://getcomposer.org/installer | php --
./composer.phar install
# create your example.php with the snippet at https://github.com/lcobucci/jwt/issues/190#issuecomment-320889845
php example.php
```

**Comment by purohitvijay** [comment] 2017-08-10 09:29
@Ocramius  its give permission error, when I use git clone git@github.com:lcobucci/jwt.git this command.
"git clone git@github.com:lcobucci/jwt.git
Cloning into 'jwt'...
Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists."

**Comment by Ocramius** [comment] 2017-08-10 09:31
You can use the `https` address too: `git clone https://github.com/lcobucci/jwt`.

**Comment by lcobucci** [comment] 2017-10-08 18:36
@purohitvijay any update on this?

**Comment by lcobucci** [comment] 2017-10-13 13:33
Well, closing here due to lack of updates. Please re-open if needed.

**Closed by lcobucci** 2017-10-13 13:33 UTC
Labels: question
