### ISSUE TITLE
expiresAt() sets a floating point value

### ISSUE THREAD

**Issue by stefanplk3** [lcobucci/jwt#693] opened 2021-02-24 15:56 UTC
$token = $config->builder()
            ->issuedBy('xy') // iss
            ->permittedFor('xy') // aud
            ->relatedTo('xy') // sub
            ->withClaim('room', '*')
            ->expiresAt($now)
            ->withHeader('kid', 'xy')
            ->getToken($config->signer(), $config->signingKey());
$token->toString() now has a floating point value in the "exp" field:

eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImtpZCI6Inh5In0.eyJpc3MiOiJ4eSIsImF1ZCI6Inh5Iiwic3ViIjoieHkiLCJyb29tIjoiKiIsImV4cCI6IjE2MTQxODI0MTIuMTI1NzgwIn0.oocn8Wg3RB8bGPeLNEPDkis9YwWPRIuNxxlXI2m3so8

{
  "iss": "xy",
  "aud": "xy",
  "sub": "xy",
  "room": "*",
  "exp": "1614182412.125780"
}

**Comment by lcobucci** [comment] 2021-02-24 16:04
Duplicate of https://github.com/lcobucci/jwt/pull/618

Also take a look at https://github.com/lcobucci/jwt/discussions/623

**Closed as completed by lcobucci** 2021-02-24 16:04 UTC
Labels: Duplicate

**Comment by lcobucci** [comment] 2021-03-19 21:03
Hello folks, thanks to @yassinrais we managed to [fix this compatibility issue whilst still preserving the microseconds precision](https://github.com/lcobucci/jwt/pull/706). We already released new versions to solve the problem.
