### ISSUE TITLE
String length limitation on secret key.

### ISSUE THREAD

**Issue by mookman288** [lcobucci/jwt#127] opened 2016-10-20 20:19 UTC
Hi, 

I'm not sure if this is the most appropriate place to post this, but because I'm primarily using PHP to generate my secret key, and this library to integrate JWT validation, it seemed like the most appropriate place. I did not see a fix for this specifically, nor did I find any other issues that match this particular "bug." I also didn't see anything in the RFC specifically mentioning key length limits. 

With that out of the way, I'm trying to integrate JWT between my API client, and API endpoint. Currently I'm just generating a string-based secret key using `openssl_random_pseudo_bytes`, converted from binary to hexadecimal. I'm using lcobucci/jwt (^3.2,) and kjur/jsrsasign (^6.1.1) from @kjur to facilitate communication. 

The issue that I'm having is that when I use a key with string length greater than 115 characters it fails validation, no matter what. If I trim the key down to 115 characters, I'm able to both sign and validate.

I just generated the following random string using the above method on PHP7 to test:

```
7e65f6f2ef2298d16b15a8788b6e1aa9ae81ac205fe959d112c75bf715af9e0a - Fails
7e65f6f2ef2298d16b15a8788b6e1aa9ae81ac205fe959d112c75bf715af9e0 - Succeeds
```

Is this a particular fault of JWT, or has anyone else experienced this?

**Comment by lcobucci** [comment] 2016-10-21 07:33
@mookman288 that sounds weird, could you send some sample tokens generated with both keys (and also say which signer you're using - I assume is HMAC-SHA*)?

**Comment by mookman288** [comment] 2016-10-21 14:14
Apologies, but you are correct. It's HMAC-SHA256, and I also tried HMAC-SHA512. 

Here's some sample tokens:

kjur/jsrsasign:

7e65f6f2ef2298d16b15a8788b6e1aa9ae81ac205fe959d112c75bf715af9e0a:
```
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJ0ZXN0IjoidGVzdCJ9.UOir1kEf5v6g-KVUdYIS4eqXei8CBdctMn5pWfiL4aPzXWFTMt7hP5a4YCes063WF8Vear4WunrCdxC-HkkZTA
```
7e65f6f2ef2298d16b15a8788b6e1aa9ae81ac205fe959d112c75bf715af9e0:
```
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJ0ZXN0IjoidGVzdCJ9.SzRW7n6I4HENi8knpS6NTCGHIT4MKgHX9UTzGZkp8O6E7eWegmkHcVHDrx18l1aGsZR07Yu6TitrPfEEiqCdAg
```

Using your library: 

7e65f6f2ef2298d16b15a8788b6e1aa9ae81ac205fe959d112c75bf715af9e0a:
```
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJ0ZXN0IjoidGVzdCJ9.-GzjQGyDbDvDw_KISK1HPHdNivRpYqNEdm5OMFputKNORSb6nv8fNj7Fk7LvRUp-djUsw346QgHECFSuFGytlA
```
7e65f6f2ef2298d16b15a8788b6e1aa9ae81ac205fe959d112c75bf715af9e0
```
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJ0ZXN0IjoidGVzdCJ9.SzRW7n6I4HENi8knpS6NTCGHIT4MKgHX9UTzGZkp8O6E7eWegmkHcVHDrx18l1aGsZR07Yu6TitrPfEEiqCdAg
```

Here's a verification tool by @kjur - https://kjur.github.io/jsrsasign/tool_jwt.html

I just noticed that the tokens are identical using the 115 character key, versus the 116 character key. That explains why the library that generated the token is the only one that can validate it when using these longer keys.

**Comment by lcobucci** [comment] 2016-10-21 14:37
It looks like a problem on @kjur's library... if you put the token generated by my lib with the key `7e65f6f2ef2298d16b15a8788b6e1aa9ae81ac205fe959d112c75bf715af9e0a` on https://jwt.io you can see that the signature is verified.

<img width="953" alt="screen shot 2016-10-21 at 16 37 12" src="https://cloud.githubusercontent.com/assets/201963/19602212/a6ffa83e-97ac-11e6-929b-dd6caf1ba23d.png">

**Comment by lcobucci** [comment] 2016-10-21 14:42
But the funny thing is that JWT.io says that they only support HS256 keys. Sorry but I have to ask... are you verifying the signature with the right signer on my lib?

**Comment by lcobucci** [comment] 2016-10-21 14:58
I've just tried a python implementation (by @jpadilla) and it works fine with the tokens generated with my lib:

```python
>>> import jwt

# Token generated with lcobucci/jwt and the right key
>>> jwt.decode('eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJ0ZXN0IjoidGVzdCJ9.-GzjQGyDbDvDw_KISK1HPHdNivRpYqNEdm5OMFputKNORSb6nv8fNj7Fk7LvRUp-djUsw346QgHECFSuFGytlA', '7e65f6f2ef2298d16b15a8788b6e1aa9ae81ac205fe959d112c75bf715af9e0a')
{u'test': u'test'}

# Token generated with lcobucci/jwt and the wrong key
>>> jwt.decode('eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJ0ZXN0IjoidGVzdCJ9.-GzjQGyDbDvDw_KISK1HPHdNivRpYqNEdm5OMFputKNORSb6nv8fNj7Fk7LvRUp-djUsw346QgHECFSuFGytlA', '7e65f6f2ef2298d16b15a8788b6e1aa9ae81ac205fe959d112c75bf715af9e0')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/jwt/api_jwt.py", line 64, in decode
    options, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jwt/api_jws.py", line 116, in decode
    key, algorithms)
  File "/usr/local/lib/python2.7/dist-packages/jwt/api_jws.py", line 186, in _verify_signature
    raise DecodeError('Signature verification failed')
jwt.exceptions.DecodeError: Signature verification failed

# Token generated with kjur/jsrsasign and the right key
>>> jwt.decode('eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJ0ZXN0IjoidGVzdCJ9.UOir1kEf5v6g-KVUdYIS4eqXei8CBdctMn5pWfiL4aPzXWFTMt7hP5a4YCes063WF8Vear4WunrCdxC-HkkZTA', '7e65f6f2ef2298d16b15a8788b6e1aa9ae81ac205fe959d112c75bf715af9e0a')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/jwt/api_jwt.py", line 64, in decode
    options, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jwt/api_jws.py", line 116, in decode
    key, algorithms)
  File "/usr/local/lib/python2.7/dist-packages/jwt/api_jws.py", line 186, in _verify_signature
    raise DecodeError('Signature verification failed')
jwt.exceptions.DecodeError: Signature verification failed
```

**Comment by lcobucci** [comment] 2016-10-21 15:00
My conclusion is that you're using the lib properly and the issue is indeed on @kjur's implementation.

I'll close this as invalid but please let me know if I might help on anything 😉

**Closed by lcobucci** 2016-10-21 15:00 UTC

**Comment by mookman288** [comment] 2016-10-21 15:09
Thank you for your diligence, I'll pass this over to @kjur and see if he's experienced this.
