### ISSUE TITLE
Cannot instantiate interface Lcobucci\JWT\Decoder

### ISSUE THREAD

**Issue by robertolanza93** [lcobucci/jwt#921] opened 2022-09-28 13:52 UTC
### Discussed in https://github.com/lcobucci/jwt/discussions/920

<div type='discussions-op-text'>

<sup>Originally posted by **robertolanza93** September 28, 2022</sup>
Hello,
I'm working with magento 2.4.4 and Lcobucci 4.2.1
when we try to use Lcobucci\JWT\Token\Parser we receive the following error:

Cannot instantiate interface Lcobucci\JWT\Decoder in /var/www/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php

can someone please help with this problem?

Thanks,
Roberto</div>

**Comment by Ocramius** [comment] 2022-09-28 14:02
Closing: please use the discussion which you already opened @ https://github.com/lcobucci/jwt/discussions/920

This is not a bug of this library.

**Closed as completed by Ocramius** 2022-09-28 14:02 UTC
Labels: Duplicate, Invalid
