### ISSUE TITLE
"Not providing the current time is deprecated. Please pass an instance of DateTimeInterface" issue

### ISSUE THREAD

**Issue by gad-rwgo** [lcobucci/jwt#610] opened 2020-12-13 01:25 UTC
Hey guys,

We have a Laravel deployment days ago and in one of our tests we found that Apple sign-in does not work. On the old server, it used to work fine but with the new one we get the error {"message": "Server Error", "status": 500} (this is an error returned when the app calls a certain route; however, I think this is not related to the root cause of the problem). We checked Laravel logs and it mentions the below error:

debug.ERROR: Not providing the current time is deprecated. Please pass an instance of DateTimeInterface. {"exception":"[object] (ErrorException(code: 0): Not providing the current time is deprecated. Please pass an instance of DateTimeInterface. at /var/www/xxx/xxx/vendor/lcobucci/jwt/src/Token.php:296)
[stacktrace]
...
...

We have absolutely no idea how to fix this. :-D Can you guys help?

Thanks,
Ten Go

**Comment by Ocramius** [comment] 2020-12-14 09:21
Sounds like you didn't commit your `composer.lock`.

Potentially duplicate of https://github.com/lcobucci/jwt/issues/550#issuecomment-733557709 - closing here.

**Closed as completed by Ocramius** 2020-12-14 09:21 UTC
Labels: Duplicate
