### ISSUE TITLE
Got secret key too short error when upgrade to 4.2.x

### ISSUE THREAD

**Issue by chan15** [lcobucci/jwt#961] opened 2022-11-03 02:04 UTC
After I upgrade the package to 4.2.1, I got the message below if I have secret key like `test`:

`Could not create token: Key provided is shorter than 256 bits, only 32 bits provided`

it's working at 4.1.x, how to fix this?

**Comment by Slamdunk** [comment] 2022-11-03 06:35
Prior to `v4.2` this library didn't follow JWT standard, allowing any key length to be used.
`v4.2` now requires a strong key, you can find the details in the docs: https://lcobucci-jwt.readthedocs.io/en/4.2.0/supported-algorithms/

For `Sha256` you can generate one from cli with `php -r 'var_dump(base64_encode(random_bytes(32)));'`, and then consuming it with `\Lcobucci\JWT\Signer\Key\InMemory::base64Encoded()`.

**Comment by Slamdunk** [comment] 2022-11-03 06:35
Duplicate of https://github.com/lcobucci/jwt/issues/890

**Closed as completed by Slamdunk** 2022-11-03 06:35 UTC
Labels: Question
