### ISSUE TITLE
Token#getClaims() returns unexpected values

### ISSUE THREAD

**Issue by schechter** [lcobucci/jwt#593] opened 2020-12-02 20:57 UTC
We've just had to pin to 3.3.3 as 3.4.1 is not behaving as expected.

`getClaims` no longer returns the expected value (perhaps only when the value is multiple lines?)

**Comment by lcobucci** [comment] 2020-12-02 21:10
That's extremely unexpected, would be able to reproduce it in a test case?

**Comment by schechter** [comment] 2020-12-03 01:17
I'll see if I can get something together, in the mean time here's some more details.
Earlier today we started getting errors in one of our staging environments.
Our composer files had `"lcobucci/jwt": "^3.2",`
The images running in production were running `"source": "https://github.com/lcobucci/jwt/tree/3.3.3"` while the environments with this errors were running `"source": "https://github.com/lcobucci/jwt/tree/3.4.1"`

We updated the composer file to pin the version to 3.3.3 and the new images resolved the issue.
I'll have to create a jwt that has a similar structure to create a test case for you.

**Comment by lcobucci** [comment] 2021-01-05 16:51
@schechter I'll be closing this since we didn't receive info on how to reproduce the issue. Feel free to open once you've got the time to help on solving this.

**Closed by lcobucci** 2021-01-05 16:51 UTC
Labels: Bug, Missing tests
